# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: 'Resourcegroup'
  displayName: 'Resource group'
  jobs:
  - job: 'Resourcegroup'
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - task: ResourceGroupCreation@1
      inputs:
        ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
        ConnectedServiceNameARM: 'Pay-As-You-Go(bba12a48-76de-4498-b0bf-77e7ce1d2b58)'
        ResourceGroupName: '$(resource_name)-$(env)-$(count)'
        ResourceLocation: 'Brazil South'
      
- stage: 'AKSregistre'
  displayName: 'AKS Registre'
  jobs:
  - job: 'aks'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'Pay-As-You-Go(bba12a48-76de-4498-b0bf-77e7ce1d2b58)'
        azureResourceGroup: '$(resource_name)-$(env)-$(count)'
        kubernetesCluster: '$(aks_name)-$(env)-$(count)'
        command: 'create'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'